# -*- coding: utf-8 -*-
"""Final Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zPojV898KBsrU-Y4KJKiYJOxXYDkVDQ_
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %pushd "/content/drive/MyDrive/Disadvantage Males/"

!pip install geojson
!pip install geodatasets
!pip install mapclassify

#Import libraries and find some data
import pandas as pd
import geojson as gpd
import geopandas as gp
import matplotlib.pyplot as plt
import mapclassify
import geopandas
import geodatasets
from geodatasets import get_path

from geodatasets import get_path

"""#Download Counties Shapefiles"""

counties = geopandas.read_file("cb_2023_us_county_500k/cb_2023_us_county_500k.shp") #Create a dataframe for analysis

counties['COUNTY_FIPS'] = counties['STATEFP'] + counties['COUNTYFP']
counties['COUNTY_FIPS'] = counties['COUNTY_FIPS'].astype(str)
cols = list(counties.columns)
cols.insert(2, cols.pop(cols.index('COUNTY_FIPS')))
counties = counties.loc[:, cols]
counties.head()

counties.plot()

"""#Downloading Disadvantage Variables"""

acs_counties = pd.read_csv("acs_counties_analysis_file.csv", dtype={'YEAR' : str,'STATE': str, 'COUNTY': str})

acs_counties = acs_counties.drop(columns= 'Unnamed: 0')

acs_counties['COUNTY_FIPS'] = acs_counties['COUNTY'].astype(str)
col = acs_counties.pop('COUNTY_FIPS')
acs_counties.insert(3, 'COUNTY_FIPS', col)
acs_counties.head()

acs_counties.dtypes

acs_counties['perc_never_married'] = acs_counties['pop_county_male_never_mar_2554'] / (acs_counties['pop_county_male_never_mar_2554'] +
                                                                                       acs_counties['pop_county_male_mar_2554']+
                                                                                       acs_counties['pop_county_male_divorced_2554'] +
                                                                                       acs_counties['pop_county_male_separated_2554']+
                                                                                       acs_counties['pop_county_male_widowed_2554']+
                                                                                       acs_counties['pop_county_male_other_2554'])

acs_counties.columns

# Pivot wider by year
#acs_counties['YEAR'] = acs_counties['YEAR'].astype(str)

acs_counties_pivot = acs_counties.pivot(index=['COUNTY_FIPS', 'STATE', 'COUNTY'], columns='YEAR', values=acs_counties.columns[4:18])

# Reset the index to make 'COUNTY_FIPS' a regular column
acs_counties_pivot = acs_counties_pivot.reset_index()

acs_counties_pivot.head()

# Rename columns by pasting together index
acs_counties_pivot.columns = [''.join(col).strip() for col in acs_counties_pivot.columns.values]
acs_counties_pivot



"""#Joining Geography with Response Variables"""

man_counties = counties.merge(acs_counties_pivot, how='left', left_on='COUNTY_FIPS', right_on='COUNTY_FIPS') #merge the dataframes to get the population and the geometry
man_counties.head()

man_counties['geometry'] = man_counties.geometry

names = man_counties.columns.tolist()
print(names)

man_counties['STATE_INT'] = man_counties['STATEFP'].astype(int)

"""##City Labels"""

# prompt: add major city labels

import matplotlib.pyplot as plt

# Assuming 'man_counties' and 'males_state_agg_pivot' are already defined and plotted as in your code.

# Add major city labels to the plots.  You'll need to define the city locations.
# Example city data (replace with your actual city data)
city_locations = {
    'New York': (-74.0060, 40.7128),  # Longitude, Latitude
    'Los Angeles': (-118.2437, 34.0522),
    'Chicago': (-87.6298, 41.8781),
    'Houston': (-95.3698, 29.7604),
    'Phoenix': (-112.0740, 33.4484),
    'Philadelphia': (-75.1652, 39.9526),
    'San Antonio': (-98.4936, 29.4241),
    'San Diego': (-117.1611, 32.7157),
    'Dallas': (-96.7970, 32.7767),
    'San Jose': (-121.8863,37.3382),
    'Austin': (-97.7431, 30.2672),
    'Jacksonville': (-81.6557, 30.3322),
    'Washington': (-77.0369, 38.9072),
    'El Paso': (-106.4813, 31.7),
    'Denver': (-104.9903, 39.7392),
    'Park City': (-111.4980, 40.6461),
    'Detroit': (-83.0458, 42.3314),
    'Seattle': (-122.3321, 47.6062),
    'Memphis': (-89.3985, 35.1936)
}



def add_city_labels(ax, city_locations, x_col='INTPTLON', y_col='INTPTLAT'):
  for city, (lon, lat) in city_locations.items():
    ax.text(lon, lat, city, fontsize=8, ha='center', va='bottom', color='black')

"""#Mapping County Level"""

man_counties[(man_counties['STATE_NAME'] != 'Alaska') & (man_counties['STATE_NAME'] != 'Hawaii')].plot('male_2564_less_ba_pct2022',
                                                                                                       figsize=(15,15),legend=True,
                                                                                                       cmap='RdBu',
                                                                                                       legend_kwds={'shrink': 0.5}) # Adjust shrink value as needed
add_city_labels(plt, city_locations) # Add city labels
plt.legend()
plt.title("Percentage of Males with No Bachelors Degree - 2022")  # Add a title
plt.show()

man_counties[(man_counties['STATE_NAME'] != 'Alaska') & (man_counties['STATE_NAME'] != 'Hawaii')].plot('male_marriage_rate_25542022',
                                                                                                       figsize=(15,15),legend=True,
                                                                                                       cmap='RdBu',
                                                                                                       legend_kwds={'shrink': 0.5}) # Adjust shrink value as needed
plt.legend()
plt.title("Male Marriage Rate - 2022")  # Add a title
plt.show()

man_counties[(man_counties['STATE_NAME'] != 'Alaska') & (man_counties['STATE_NAME'] != 'Hawaii')].plot('perc_never_married2022',
                                                                                                       figsize=(15,15),legend=True,
                                                                                                       cmap='RdBu',
                                                                                                       legend_kwds={'shrink': 0.5}) # Adjust shrink value as needed

plt.legend()
add_city_labels(plt, city_locations) # Add city labels

plt.title("Percentage of Males Who Have Never Married - 2022")  # Add a title
plt.show()

man_counties[(man_counties['STATE_NAME'] != 'Alaska') & (man_counties['STATE_NAME'] != 'Hawaii')].plot('opm_male_25542022',
                                                                                                       figsize=(15,15),legend=True,
                                                                                                       cmap='RdBu',
                                                                                                       legend_kwds={'shrink': 0.5}) # Adjust shrink value as needed
add_city_labels(plt, city_locations) # Add city labels

plt.legend()
plt.title("Percentage of Males Below the Poverty Line - 2022")  # Add a title
plt.show()

"""#Histograms"""

man_counties['male_2564_less_ba_pct2022'].plot.hist(bins=100, color = "cornflowerblue")

plt.title("Percentage of Males with No Bachelors Degree - 2022")

man_counties['male_marriage_rate_25542022'].plot.hist(bins=100, color = "lightcoral")

plt.title("Male Marriage Rate - 2022")

man_counties['opm_male_25542022'].plot.hist(bins=100, color = "darkred")

plt.title("Percentage of Males Below the Poverty Line - 2022")



"""#import state aggregates"""

males_state_agg = pd.read_csv('males_state_agg.csv', dtype={'STATE': str})  # Replace with your file's name
males_state_agg_pivot = pd.read_csv('males_state_agg_pivot.csv', dtype={'STATE': str})  # Replace with your file's name

males_state_agg_pivot = counties.merge(males_state_agg_pivot, how='left', left_on='STATEFP', right_on='STATE') #merge the dataframes to get the population and the geometry

names = males_state_agg_pivot.columns.tolist()
print(names)
males_state_agg_pivot.head()

names = males_state_agg.columns.tolist()
print(names)

"""#Mapping State Level"""

males_state_agg_pivot[(males_state_agg_pivot['STATE_NAME'] != 'Alaska') & (males_state_agg_pivot['STATE_NAME'] != 'Hawaii')].plot('male_2564_less_ba_pct_2022',
                                                                                                       figsize=(15,15),legend=True,
                                                                                                       cmap='RdBu',
                                                                                                       legend_kwds={'shrink': 0.5}) # Adjust shrink value as needed
plt.legend()
plt.title("Percentage of Males With No Bachelors Degree - 2022")  # Add a title
plt.show()

males_state_agg_pivot[(males_state_agg_pivot['STATE_NAME'] != 'Alaska') & (males_state_agg_pivot['STATE_NAME'] != 'Hawaii')].plot('male_marriage_rate_2554_2022',
                                                                                                       figsize=(15,15),legend=True,
                                                                                                       cmap='RdBu',
                                                                                                       legend_kwds={'shrink': 0.5}) # Adjust shrink value as needed
plt.legend()
plt.title("Male Marriage Rate - 2022")  # Add a title
plt.show()

males_state_agg_pivot[(males_state_agg_pivot['STATE_NAME'] != 'Alaska') & (males_state_agg_pivot['STATE_NAME'] != 'Hawaii')].plot('perc_never_married_2022',
                                                                                                       figsize=(15,15),legend=True,
                                                                                                       cmap='RdBu',
                                                                                                       legend_kwds={'shrink': 0.5}) # Adjust shrink value as needed
add_city_labels(plt, city_locations) # Add city labels

plt.legend()
plt.title("Percentage of Males Who Have Never Been Married - 2022")  # Add a title
plt.show()

males_state_agg_pivot[(males_state_agg_pivot['STATE_NAME'] != 'Alaska') & (males_state_agg_pivot['STATE_NAME'] != 'Hawaii')].plot('opm_male_2554_2022',
                                                                                                       figsize=(15,15),legend=True,
                                                                                                       cmap='RdBu',
                                                                                                       legend_kwds={'shrink': 0.5}) # Adjust shrink value as needed
add_city_labels(plt, city_locations) # Add city labels
plt.legend()
plt.title("Percentage of Males Below the Poverty Line -")  # Add a title
plt.show()

"""##Mapping State Density"""

vars

state_disadvanted_totals_2022 = acs_counties[ acs_counties['YEAR'] == '2022'].groupby('STATE')[['male_2564_less_ba', 'pop_opm_county_male_2554', 'pop_county_male_mar_2554']].sum()
state_disadvanted_totals_2022.head()

us_disadvantaged_totals_2022 = state_disadvanted_totals_2022.sum()
us_disadvantaged_totals_2022

males_state_agg_pivot['state_share_less_ba_2022'] = males_state_agg_pivot['male_2564_less_ba_2022'] / 57615871
males_state_agg_pivot['state_share_opm_2022'] = males_state_agg_pivot['pop_opm_county_male_2554_2022']/5526833
males_state_agg_pivot['state_share_marriage_2022'] = males_state_agg_pivot['pop_county_male_mar_2554_2022']/32584908.0

males_state_agg_pivot[['STATE','COUNTY_FIPS','state_share_less_ba_2022','state_share_opm_2022','state_share_marriage_2022']].head()

males_state_agg_pivot[(males_state_agg_pivot['STATE_NAME'] != 'Alaska') & (males_state_agg_pivot['STATE_NAME'] != 'Hawaii')].plot('state_share_less_ba_2022',
                                                                                                       figsize=(15,15),legend=True,
                                                                                                       cmap='RdBu',
                                                                                                       legend_kwds={'shrink': 0.5}) # Adjust shrink value as needed
add_city_labels(plt, city_locations) # Add city labels

plt.legend()
plt.title("Share of Males With No Bachelors Degree - 2022")  # Add a title
plt.show()

males_state_agg_pivot[(males_state_agg_pivot['STATE_NAME'] != 'Alaska') & (males_state_agg_pivot['STATE_NAME'] != 'Hawaii')].plot('state_share_opm_2022',
                                                                                                       figsize=(15,15),legend=True,
                                                                                                       cmap='RdBu',
                                                                                                       legend_kwds={'shrink': 0.5}) # Adjust shrink value as needed
add_city_labels(plt, city_locations) # Add city labels

plt.legend()
plt.title("Share of Males in Poverty - 2022")  # Add a title
plt.show()

males_state_agg_pivot[(males_state_agg_pivot['STATE_NAME'] != 'Alaska') & (males_state_agg_pivot['STATE_NAME'] != 'Hawaii')].plot('state_share_marriage_2022',
                                                                                                       figsize=(15,15),legend=True,
                                                                                                       cmap='RdBu',
                                                                                                       legend_kwds={'shrink': 0.5}) # Adjust shrink value as needed
add_city_labels(plt, city_locations) # Add city labels

plt.legend()
plt.title("Share of Males Who are Married - 2022")  # Add a title
plt.show()

"""#Descriptive Statistics"""

vars = ['male_2564_less_ba_pct','opm_male_2554', 'male_marriage_rate_2554', 'perc_never_married']
acs_counties[ acs_counties['YEAR'] == '2022'][['male_2564_less_ba_pct','opm_male_2554', 'male_marriage_rate_2554', 'perc_never_married' ]].describe().transpose()

acs_counties.columns

acs_counties[ acs_counties['YEAR'] == '2022'].iloc[:, 4:20].describe().transpose()

"""##Correlation Matrix fix"""

vars = ['male_2564_less_ba_pct',
 'opm_male_2554',
 'male_marriage_rate_2554']

# Correlation Matrix

corr_matrix = acs_counties[acs_counties['YEAR'] == '2022'][vars].corr()
corr_matrix

# Visualization of the Correlation Matrix (optional)
plt.figure(figsize=(12, 10))
plt.imshow(corr_matrix, cmap='coolwarm', interpolation='nearest')
plt.colorbar()
plt.xticks(range(len(corr_matrix.columns)), corr_matrix.columns, rotation=45)
plt.yticks(range(len(corr_matrix.columns)), corr_matrix.columns)
plt.title('Correlation Matrix of Disadvantage Metrics')
plt.show()

"""#Subgroup Analysis

##importing demographic data
"""

census_county_pop = pd.read_csv('census_county_pop.csv', dtype={'STATEFP': str, 'COUNTYFP': str,'COUNTY_FIPS':str})  # Replace with your file's name

census_county_pop = census_county_pop.drop(columns= 'Unnamed: 0')

census_county_pop.head()

"""##merging demographics to variables"""

dem_merge = acs_counties[acs_counties['YEAR'] == '2022'].merge(census_county_pop, how='left', left_on='COUNTY_FIPS', right_on='COUNTY_FIPS')

dem_merge.head()

dem_merge[['PERC_WHITE', 'PERC_BLACK', 'PERC_ASIAN', 'PERC_NAT_HAW', 'PERC_AM_IND',
       'PERC_TWO_RACE', 'PERC_OTHER', 'PERC_HISP_LAT']].describe().transpose()

"""#race frequencies"""

races = ('PERC_WHITE', 'PERC_BLACK', 'PERC_ASIAN', 'PERC_NAT_HAW', 'PERC_AM_IND',
       'PERC_TWO_RACE', 'PERC_OTHER', 'PERC_HISP_LAT')

for i in races:
  dem_merge[i].plot.hist(bins = 25)
  title = i
  plt.title(title)
  plt.show()

vars = ['male_2564_less_ba_pct','opm_male_2554', 'male_marriage_rate_2554', 'perc_never_married']

marriage_sub = pd.DataFrame({'Black' : dem_merge[dem_merge['PERC_BLACK'] > 15][vars].mean(),
                           'Latino' : dem_merge[dem_merge['PERC_HISP_LAT'] > 15][vars].mean(),
                           'Native' : dem_merge[dem_merge['PERC_AM_IND'] > 5][vars].mean(),
                           'Asian' : dem_merge[dem_merge['PERC_ASIAN'] > 5][vars].mean(),
                           'Average' : dem_merge[vars].mean()})
#
marriage_sub2 = pd.DataFrame({'Black' : dem_merge[dem_merge['PERC_BLACK'] > 20][vars].mean(),
                           'Latino' : dem_merge[dem_merge['PERC_HISP_LAT'] > 20][vars].mean(),
                           'Native' : dem_merge[dem_merge['PERC_AM_IND'] > 10][vars].mean(),
                           'Asian' : dem_merge[dem_merge['PERC_ASIAN'] > 10][vars].mean(),
                           'Average' : dem_merge[vars].mean()})
#

marriage_sub2.plot.bar(grid=True,)
plt.xticks(rotation=20)

"""#full features join

beginning with dem_merge, which contains acs disadvantage metrics from 2022 and demographic data from 2020, I will join with economic, housing, and ADI tables
"""

economic_features = pd.read_csv('economic_features.csv', dtype={'STATEFP': str, 'COUNTYFP': str,'COUNTY_FIPS':str})
housing_features = pd.read_csv('housing_features.csv', dtype={'STATEFP': str, 'COUNTYFP': str,'COUNTY_FIPS':str})
ADI_ranks_county = pd.read_csv('ADI_ranks_county.csv', dtype={'STATEFP': str, 'COUNTYFP': str,'COUNTY_FIPS':str})



ADI_ranks_county = ADI_ranks_county[['STATEFP', 'COUNTYFP', 'COUNTY_FIPS',
       'ADI_NATRANK_2022', 'ADI_STATERNK_2022']]
ADI_ranks_county

economic_features.head()

housing_features.head()

ADI_ranks_county.head()

column_to_move = dem_merge.pop("STATEFP")
dem_merge.insert(4, "STATEFP", column_to_move)
column_to_move = dem_merge.pop("COUNTYFP")
dem_merge.insert(5, "COUNTYFP", column_to_move)

dem_percentages = dem_merge.drop(columns=['COUNTY_TOTAL',
       'MALES_COUNT', 'FEMALES_COUNT', 'ADULT_MALES', 'ADULT_FEMALES','WHITE', 'BLACK', 'ASIAN',
       'NAT_HAW', 'AM_IND', 'TWO_RACE', 'OTHER', 'HISP_LAT',])
dem_percentages.head()

full_feature = dem_percentages.merge(economic_features,
                               how='left', left_on=['STATEFP','COUNTYFP','COUNTY_FIPS'],
                               right_on=['STATEFP','COUNTYFP','COUNTY_FIPS']).drop(columns=['County', 'Over_16'])


full_feature = full_feature.merge(housing_features,
                                  how='left', left_on=['STATEFP','COUNTYFP','COUNTY_FIPS'],
                                  right_on=['STATEFP','COUNTYFP','COUNTY_FIPS']). drop(columns=['County_Name', 'State_Name',])

full_feature = full_feature.merge(ADI_ranks_county, how='left', left_on=['STATEFP','COUNTYFP','COUNTY_FIPS'],
                                  right_on=['STATEFP','COUNTYFP','COUNTY_FIPS'])

column_to_move = full_feature.pop("County")
full_feature.insert(6, "County", column_to_move)
print(full_feature.shape)

full_feature.to_csv('full_feature.csv', index=False)  # Set index=False to avoid saving the DataFrame index

"""#clustering"""

len(full_feature.columns.tolist())
cluster_features = full_feature.columns.tolist()[21:128]
len(cluster_features)

full_feature.columns.tolist()[21:128]

cluster_features = full_feature.columns.tolist()[21:128]
cluster_features

from sklearn.cluster import KMeans
import numpy as np

# Assuming 'man_counties' DataFrame is already loaded and preprocessed as in the provided code.

# Select features for clustering (replace with your desired features)



cluster_features = full_feature.columns.tolist()[21:128] # Example features
X = full_feature[cluster_features].dropna()  # Remove rows with missing values in selected features

X.shape

# Determine optimal number of clusters (e.g., using the Elbow method)
inertia = []
for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=0)
    kmeans.fit(X)
    inertia.append(kmeans.inertia_)

# Plot inertia to find the elbow point
plt.plot(range(1, 11), inertia, marker='o')
plt.title('Elbow Method for Optimal k')
plt.xlabel('Number of clusters')
plt.ylabel('Inertia')
plt.show()

# Based on the elbow method, choose the optimal number of clusters (e.g., k=3)
optimal_k = 4  # Replace with the value you determined from the elbow method plot

# Perform KMeans clustering
kmeans = KMeans(n_clusters=optimal_k, random_state=0)
full_feature['cluster'] = np.nan # Initialize a new column for cluster assignments
full_feature.loc[X.index, 'cluster'] = kmeans.fit_predict(X)

"""#Cluster Map"""

full_feature_geo = counties.merge(full_feature, how='left', left_on=['STATEFP',	'COUNTYFP',	'COUNTY_FIPS'], right_on=['STATEFP',	'COUNTYFP',	'COUNTY_FIPS'])

# Analyze and visualize the clusters
# Example: plot the clusters on a map colored by cluster assignment
full_feature_geo[(full_feature_geo['STATE'] != '02')&(full_feature_geo['STATE'] != '15')].plot(column='cluster',
                                                                                               categorical=True,
                                                                                               legend=True,
                                                                                               cmap='Paired')  # Adjust cmap as desired
plt.title(f'KMeans Clusters (k={optimal_k})')
plt.show()

"""#Cluster Breakdown"""

dis_cluster = full_feature.groupby('cluster')[vars].mean()
dis_cluster

plt.figure(figsize=(12, 10))
plt.imshow(dis_cluster, cmap='coolwarm', interpolation='nearest', label = True)
plt.colorbar()
plt.xticks(range(len(dis_cluster.columns)), dis_cluster.columns, rotation=45)
plt.yticks(range(0,4), ['Cluster 0','Cluster 1','Cluster 2','Cluster 3'])
plt.title('Mean of Disadvantage Variables for Each Cluster')
plt.show()

races = ['PERC_BLACK', 'PERC_ASIAN', 'PERC_NAT_HAW', 'PERC_AM_IND',
       'PERC_TWO_RACE', 'PERC_OTHER', 'PERC_HISP_LAT']

race_cluster = full_feature.groupby('cluster')[races].mean()

plt.imshow(race_cluster, cmap='coolwarm', interpolation='nearest', label = True)
plt.colorbar()
plt.xticks(range(len(race_cluster.columns)), race_cluster.columns, rotation=45)
plt.yticks(range(0,3), ['Cluster 0','Cluster 1','Cluster 2'])
plt.title('Racial Makeup of Each Cluster')

"""#random forest 1

##less ba rf
"""

# prompt: random forest to predict male_marriage_rate_2554

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Prepare the data
features = cluster_features
target = 'male_2564_less_ba_pct'

X = full_feature[features].dropna()
y = full_feature.loc[X.index, target]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # 80% train, 20% test

# Initialize and train the Random Forest Regressor
rf_model = RandomForestRegressor(n_estimators=100, random_state=42) # You can adjust n_estimators
rf_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = rf_model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

# Feature Importance
feature_importances = rf_model.feature_importances_

less_ba_feature_importance = pd.DataFrame({"Feature" : features, "Importance": feature_importances}).sort_values(by='Importance', ascending=False)
less_ba_feature_importance.head(10)

"""##opm rf"""

# prompt: random forest to predict male_marriage_rate_2554

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Prepare the data
features = cluster_features
target = 'opm_male_2554'

X = full_feature[features].dropna()
y = full_feature.loc[X.index, target]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # 80% train, 20% test

# Initialize and train the Random Forest Regressor
rf_model = RandomForestRegressor(n_estimators=100, random_state=42) # You can adjust n_estimators
rf_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = rf_model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

# Feature Importance
feature_importances2 = rf_model.feature_importances_

poverty_feature_importance = pd.DataFrame({"Feature" : features, "Importance": feature_importances2}).sort_values(by='Importance', ascending=False)
poverty_feature_importance.head(10)

"""##marriage rf"""

# prompt: random forest to predict male_marriage_rate_2554

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Prepare the data
features = cluster_features
target = 'male_marriage_rate_2554'

X = full_feature[features].dropna()
y = full_feature.loc[X.index, target]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # 80% train, 20% test

# Initialize and train the Random Forest Regressor
rf_model = RandomForestRegressor(n_estimators=100, random_state=42) # You can adjust n_estimators
rf_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = rf_model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

# Feature Importance
feature_importances3 = rf_model.feature_importances_

marriage_feature_importance = pd.DataFrame({"Feature" : features, "Importance": feature_importances3}).sort_values(by='Importance', ascending=False)
marriage_feature_importance.head(10)

"""#RF Graphs"""

less_ba_feature_importance.head()['Feature'].tolist()

for i in less_ba_feature_importance.head()['Feature'].tolist():
  plt.scatter( full_feature[i], full_feature['male_2564_less_ba_pct'], color = 'cornflowerblue')
  plt.xlabel(i)
  plt.ylabel('Percentage of Males Without Bachelors Degree')
  plt.show()

for i in poverty_feature_importance.head()['Feature'].tolist():
  plt.scatter( full_feature[i], full_feature['opm_male_2554'], color = 'darkred')
  plt.xlabel(i)
  plt.ylabel('Percentage of Males In Poverty')
  plt.show()

for i in marriage_feature_importance.head()['Feature'].tolist():
  plt.scatter( full_feature[i], full_feature['male_marriage_rate_2554'], color = 'lightcoral')
  plt.xlabel(i)
  plt.ylabel('Percentage of Males Who are Married')
  plt.show()